In [1]:
import pandas as pd
df=pd.read_csv('/content/12. 100_Unique_QA_Dataset.csv')
df.head()

                                          question      answer
0                   What is the capital of France?       Paris
1                  What is the capital of Germany?      Berlin
2               Who wrote 'To Kill a Mockingbird'?  Harper-Lee
3  What is the largest planet in our solar system?     Jupiter
4   What is the boiling point of water in Celsius?         100

In [2]:
##words to numbers
#tokenize
def tokenize(text):
  text=text.lower()
  text=text.replace('?','')    #data preprocessing
  text=text.replace("'","")

  return text.split()

In [3]:
#vocab
vocab={'<UNK>': 0}   #for unknown ques

def build_vocab(row):

  tokenized_question=tokenize(row['question'])
  tokenized_answer=tokenize(row['answer'])
  merged_tokens=tokenized_question+tokenized_answer
  print(merged_tokens)

  for token in merged_tokens:
    if token not in vocab:
      vocab[token]=len(vocab)

In [4]:
df.apply(build_vocab,axis=1)

['what', 'is', 'the', 'capital', 'of', 'france', 'paris']
['what', 'is', 'the', 'capital', 'of', 'germany', 'berlin']
['who', 'wrote', 'to', 'kill', 'a', 'mockingbird', 'harper-lee']
['what', 'is', 'the', 'largest', 'planet', 'in', 'our', 'solar', 'system', 'jupiter']
['what', 'is', 'the', 'boiling', 'point', 'of', 'water', 'in', 'celsius', '100']
['who', 'painted', 'the', 'mona', 'lisa', 'leonardo-da-vinci']
['what', 'is', 'the', 'square', 'root', 'of', '64', '8']
['what', 'is', 'the', 'chemical', 'symbol', 'for', 'gold', 'au']
['which', 'year', 'did', 'world', 'war', 'ii', 'end', '1945']
['what', 'is', 'the', 'longest', 'river', 'in', 'the', 'world', 'nile']
['what', 'is', 'the', 'capital', 'of', 'japan', 'tokyo']
['who', 'developed', 'the', 'theory', 'of', 'relativity', 'albert-einstein']
['what', 'is', 'the', 'freezing', 'point', 'of', 'water', 'in', 'fahrenheit', '32']
['which', 'planet', 'is', 'known', 'as', 'the', 'red', 'planet', 'mars']
['who', 'is', 'the', 'author', 'of', '1984', 'george-orwell']
['what', 'is', 'the', 'currency', 'of', 'the', 'united', 'kingdom', 'pound']
['what', 'is', 'the', 'capital', 'of', 'india', 'delhi']
['who', 'discovered', 'gravity', 'newton']
['how', 'many', 'continents', 'are', 'there', 'on', 'earth', '7']
['which', 'gas', 'do', 'plants', 'use', 'for', 'photosynthesis', 'co2']
['what', 'is', 'the', 'smallest', 'prime', 'number', '2']
['who', 'invented', 'the', 'telephone', 'alexander-graham-bell']
['what', 'is', 'the', 'capital', 'of', 'australia', 'canberra']
['which', 'ocean', 'is', 'the', 'largest', 'pacific-ocean']
['what', 'is', 'the', 'speed', 'of', 'light', 'in', 'vacuum', '299,792,458m/s']
['which', 'language', 'is', 'spoken', 'in', 'brazil', 'portuguese']
['who', 'discovered', 'penicillin', 'alexander-fleming']
['what', 'is', 'the', 'capital', 'of', 'canada', 'ottawa']
['what', 'is', 'the', 'largest', 'mammal', 'on', 'earth', 'whale']
['which', 'element', 'has', 'the', 'atomic', 'number', '1', 'hydrogen']
['what', 'is', 'the', 'tallest', 'mountain', 'in', 'the', 'world', 'everest']
['which', 'city', 'is', 'known', 'as', 'the', 'big', 'apple', 'newyork']
['how', 'many', 'planets', 'are', 'in', 'the', 'solar', 'system', '8']
['who', 'painted', 'starry', 'night', 'vangogh']
['what', 'is', 'the', 'chemical', 'formula', 'of', 'water', 'h2o']
['what', 'is', 'the', 'capital', 'of', 'italy', 'rome']
['which', 'country', 'is', 'famous', 'for', 'sushi', 'japan']
['who', 'was', 'the', 'first', 'person', 'to', 'step', 'on', 'the', 'moon', 'armstrong']
['what', 'is', 'the', 'main', 'ingredient', 'in', 'guacamole', 'avocado']
['how', 'many', 'sides', 'does', 'a', 'hexagon', 'have', '6']
['what', 'is', 'the', 'currency', 'of', 'china', 'yuan']
['who', 'wrote', 'pride', 'and', 'prejudice', 'jane-austen']
['what', 'is', 'the', 'chemical', 'symbol', 'for', 'iron', 'fe']
['what', 'is', 'the', 'hardest', 'natural', 'substance', 'on', 'earth', 'diamond']
['which', 'continent', 'is', 'the', 'largest', 'by', 'area', 'asia']
['who', 'was', 'the', 'first', 'president', 'of', 'the', 'united', 'states', 'george-washington']
['which', 'bird', 'is', 'known', 'for', 'its', 'ability', 'to', 'mimic', 'sounds', 'parrot']
['what', 'is', 'the', 'longest-running', 'animated', 'tv', 'show', 'simpsons']
['what', 'is', 'the', 'smallest', 'country', 'in', 'the', 'world', 'vaticancity']
['which', 'planet', 'has', 'the', 'most', 'moons', 'saturn']
['who', 'wrote', 'romeo', 'and', 'juliet', 'shakespeare']
['what', 'is', 'the', 'main', 'gas', 'in', 'earths', 'atmosphere', 'nitrogen']
['how', 'many', 'bones', 'are', 'in', 'the', 'adult', 'human', 'body', '206']
['which', 'metal', 'is', 'a', 'liquid', 'at', 'room', 'temperature', 'mercury']
['what', 'is', 'the', 'capital', 'of', 'russia', 'moscow']
['who', 'discovered', 'electricity', 'benjamin-franklin']
['which', 'is', 'the', 'second-largest', 'country', 'by', 'land', 'area', 'canada']
['what', 'is', 'the', 'color', 'of', 'a', 'ripe', 'banana', 'yellow']
['which', 'month', 'has', '28', 'days', 'in', 'a', 'common', 'year', 'february']
['what', 'is', 'the', 'study', 'of', 'living', 'organisms', 'called', 'biology']
['which', 'country', 'is', 'home', 'to', 'the', 'great', 'wall', 'china']
['what', 'do', 'bees', 'collect', 'from', 'flowers', 'nectar']
['what', 'is', 'the', 'opposite', 'of', 'day', 'night']
['what', 'is', 'the', 'capital', 'of', 'south', 'korea', 'seoul']
['who', 'invented', 'the', 'light', 'bulb', 'edison']
['which', 'gas', 'do', 'humans', 'breathe', 'in', 'for', 'survival', 'oxygen']
['what', 'is', 'the', 'square', 'root', 'of', '144', '12']
['which', 'country', 'has', 'the', 'pyramids', 'of', 'giza', 'egypt']
['which', 'sea', 'creature', 'has', 'eight', 'arms', 'octopus']
['which', 'holiday', 'is', 'celebrated', 'on', 'december', '25', 'christmas']
['what', 'is', 'the', 'currency', 'of', 'japan', 'yen']
['how', 'many', 'legs', 'does', 'a', 'spider', 'have', '8']
['which', 'sport', 'uses', 'a', 'net,', 'ball,', 'and', 'hoop', 'basketball']
['which', 'country', 'is', 'famous', 'for', 'its', 'kangaroos', 'australia']
['who', 'was', 'the', 'first', 'female', 'prime', 'minister', 'of', 'the', 'uk', 'margaretthatcher']
['which', 'is', 'the', 'fastest', 'land', 'animal', 'cheetah']
['what', 'is', 'the', 'first', 'element', 'on', 'the', 'periodic', 'table', 'hydrogen']
['what', 'is', 'the', 'capital', 'of', 'spain', 'madrid']
['which', 'planet', 'is', 'the', 'closest', 'to', 'the', 'sun', 'mercury']
['who', 'is', 'known', 'as', 'the', 'father', 'of', 'computers', 'charlesbabbage']
['what', 'is', 'the', 'capital', 'of', 'mexico', 'mexicocity']
['how', 'many', 'colors', 'are', 'in', 'a', 'rainbow', '7']
['which', 'musical', 'instrument', 'has', 'black', 'and', 'white', 'keys', 'piano']
['who', 'discovered', 'the', 'americas', 'in', '1492', 'christophercolumbus']
['which', 'disney', 'character', 'has', 'a', 'long', 'nose', 'and', 'grows', 'it', 'when', 'lying', 'pinocchio']
['who', 'directed', 'the', 'movie', 'titanic', 'jamescameron']
['which', 'superhero', 'is', 'also', 'known', 'as', 'the', 'dark', 'knight', 'batman']
['what', 'is', 'the', 'capital', 'of', 'brazil', 'brasilia']
['which', 'fruit', 'is', 'known', 'as', 'the', 'king', 'of', 'fruits', 'mango']
['which', 'country', 'is', 'known', 'for', 'the', 'eiffel', 'tower', 'france']

0     None
1     None
2     None
3     None
4     None
      ...
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [5]:
len(vocab)

324

In [6]:
#conv words to num indices
def text_to_indices(text,vocab):
  indexed_text=[]

  for token in tokenize(text):
    if token in vocab:
      indexed_text.append(vocab[token]) #adding index of word from vocab
    else:
      indexed_text.append(vocab['<UNK>'])  #ret 0 for unindexed words
  return indexed_text

In [7]:
text_to_indices("what is campusx",vocab)

[1, 2, 0]

In [8]:
import torch
from torch.utils.data import Dataset,DataLoader

In [9]:
class QADataset(Dataset):
  def __init__(self,df,vocab):
    self.df=df
    self.vocab=vocab

  def __len__(self):
    return self.df.shape[0]

  def __getitem__(self,index):
    numerical_question=text_to_indices(self.df.iloc[index]['question'],self.vocab)
    numerical_answer=text_to_indices(self.df.iloc[index]['answer'],self.vocab)

    return torch.tensor(numerical_question),torch.tensor(numerical_answer)

In [10]:
dataset=QADataset(df,vocab)

In [11]:
dataset[0]

(tensor([1, 2, 3, 4, 5, 6]), tensor([7]))

In [12]:
dataloader=DataLoader(dataset,batch_size=1,shuffle=True)

In [23]:
for question,answer in dataloader:
  print(question,answer[0])

tensor([[ 42, 101,   2,   3,  17]]) tensor([102])
tensor([[ 78,  79, 129,  81,  19,   3,  21,  22]]) tensor([36])
tensor([[ 78,  79, 261, 151,  14, 262, 153]]) tensor([36])
tensor([[ 1,  2,  3, 92, 93, 94]]) tensor([95])
tensor([[ 10,  11, 189, 158, 190]]) tensor([191])
tensor([[1, 2, 3, 4, 5, 6]]) tensor([7])
tensor([[  1,   2,   3,   4,   5, 236, 237]]) tensor([238])
tensor([[ 1,  2,  3, 37, 38, 39, 40]]) tensor([41])
tensor([[ 1,  2,  3, 69,  5,  3, 70, 71]]) tensor([72])
tensor([[ 42, 137,   2,  62,  39,   3, 322, 323]]) tensor([6])
tensor([[ 1,  2,  3, 50, 51, 19,  3, 45]]) tensor([52])
tensor([[ 1,  2,  3, 59, 25,  5, 26, 19, 60]]) tensor([61])
tensor([[10, 55,  3, 56,  5, 57]]) tensor([58])
tensor([[ 42, 299, 300, 118,  14, 301, 302, 158, 303, 304, 305, 306]]) tensor([307])
tensor([[  1,   2,   3, 141, 117,  83,   3, 277, 278]]) tensor([121])
tensor([[ 10, 140,   3, 141, 142,  12, 143,  83,   3, 144]]) tensor([145])
tensor([[  1,   2,   3,  37,  38,  39, 161]]) tensor([162])
tensor([[  1,   2,   3,  69,   5, 155]]) tensor([156])
tensor([[ 10, 308,   3, 309, 310]]) tensor([311])
tensor([[ 78,  79, 150, 151,  14, 152, 153]]) tensor([154])
tensor([[10,  2,  3, 66,  5, 67]]) tensor([68])
tensor([[ 10,  11, 157, 158, 159]]) tensor([160])
tensor([[  1,   2,   3, 103,   5, 104,  19, 105]]) tensor([106])
tensor([[  1,   2,   3,  37, 133,   5,  26]]) tensor([134])
tensor([[ 42, 137,   2, 138,  39, 139]]) tensor([53])
tensor([[ 42, 312,   2, 313,  62,  63,   3, 314, 315]]) tensor([316])
tensor([[ 42, 200,   2,  14, 201, 202, 203, 204]]) tensor([205])
tensor([[ 78,  79, 288,  81,  19,  14, 289]]) tensor([85])
tensor([[ 10,  75,   3, 296,  19, 297]]) tensor([298])
tensor([[42, 18,  2, 62, 63,  3, 64, 18]]) tensor([65])
tensor([[ 42, 318,   2,  62,  63,   3, 319,   5, 320]]) tensor([321])
tensor([[ 42,  18,   2,   3, 281,  12,   3, 282]]) tensor([205])
tensor([[ 42, 167,   2,   3,  17, 168, 169]]) tensor([170])
tensor([[ 1,  2,  3, 33, 34,  5, 35]]) tensor([36])
tensor([[42, 43, 44, 45, 46, 47, 48]]) tensor([49])
tensor([[ 10,  75, 111]]) tensor([112])
tensor([[10, 11, 12, 13, 14, 15]]) tensor([16])
tensor([[  1,   2,   3, 180, 181, 182, 183]]) tensor([184])
tensor([[ 1,  2,  3,  4,  5, 73]]) tensor([74])
tensor([[10, 29,  3, 30, 31]]) tensor([32])
tensor([[  1,   2,   3,   4,   5, 286]]) tensor([287])
tensor([[ 10, 140,   3, 141, 270,  93, 271,   5,   3, 272]]) tensor([273])
tensor([[  1,   2,   3,   4,   5, 206]]) tensor([207])
tensor([[ 1,  2,  3, 17, 18, 19, 20, 21, 22]]) tensor([23])
tensor([[  1,   2,   3, 234,   5, 235]]) tensor([131])
tensor([[ 1,  2,  3, 69,  5, 53]]) tensor([260])
tensor([[ 42, 125,   2,  62,  63,   3, 126, 127]]) tensor([128])
tensor([[42, 86, 87, 88, 89, 39, 90]]) tensor([91])
tensor([[ 1,  2,  3,  4,  5, 99]]) tensor([100])
tensor([[  1,   2,   3, 122, 123,  19,   3,  45]]) tensor([124])
tensor([[ 10,  29, 130, 131]]) tensor([132])
tensor([[ 10,  75, 208]]) tensor([209])
tensor([[10, 96,  3, 97]]) tensor([98])
tensor([[ 10, 140,   3, 141, 171,   5,   3,  70, 172]]) tensor([173])
tensor([[  1,   2,   3, 163, 164, 165,  83,  84]]) tensor([166])
tensor([[  1,   2,   3,   4,   5, 135]]) tensor([136])
tensor([[  1,   2,   3, 212,   5,  14, 213, 214]]) tensor([215])
tensor([[ 42, 290, 291, 118, 292, 158, 293, 294]]) tensor([295])
tensor([[ 42,   2,   3, 210, 137, 168, 211, 169]]) tensor([113])
tensor([[ 42, 216, 118, 217, 218,  19,  14, 219,  43]]) tensor([220])
tensor([[ 42,   2,   3, 274, 211, 275]]) tensor([276])
tensor([[ 1,  2,  3,  4,  5, 53]]) tensor([54])
tensor([[ 1,  2,  3, 24, 25,  5, 26, 19, 27]]) tensor([28])
tensor([[ 42, 250, 251, 118, 252, 253]]) tensor([254])
tensor([[ 10,   2,  62,  63,   3, 283,   5, 284]]) tensor([285])
tensor([[  1,   2,   3, 146,  86,  19, 192, 193]]) tensor([194])
tensor([[ 78,  79, 195,  81,  19,   3, 196, 197, 198]]) tensor([199])
tensor([[  1,   2,   3,   4,   5, 113]]) tensor([114])
tensor([[10, 75, 76]]) tensor([77])
tensor([[ 42,  86,  87, 241, 242,  19,  39, 243]]) tensor([244])
tensor([[  1,   2,   3, 221,   5, 222, 223, 224]]) tensor([225])
tensor([[  1,   2,   3,   4,   5, 279]]) tensor([280])
tensor([[ 42, 107,   2, 108,  19, 109]]) tensor([110])
tensor([[  1,   2,   3,  17, 115,  83,  84]]) tensor([116])
tensor([[ 42, 117, 118,   3, 119,  94, 120]]) tensor([121])
tensor([[ 42, 263, 264,  14, 265, 266, 158, 267]]) tensor([268])
tensor([[ 10,  96,   3, 104, 239]]) tensor([240])
tensor([[  1,  87, 229, 230, 231, 232]]) tensor([233])
tensor([[ 42, 137,   2, 138,  39, 175, 269]]) tensor([99])
tensor([[ 42,  18, 118,   3, 186, 187]]) tensor([188])
tensor([[78, 79, 80, 81, 82, 83, 84]]) tensor([85])
tensor([[  1,   2,   3,   4,   5, 109]]) tensor([317])
tensor([[ 42, 174,   2,  62,  39, 175, 176,  12, 177, 178]]) tensor([179])
tensor([[1, 2, 3, 4, 5, 8]]) tensor([9])
tensor([[ 42, 255,   2, 256,  83, 257, 258]]) tensor([259])
tensor([[ 42, 137, 118,   3, 247,   5, 248]]) tensor([249])
tensor([[  1,   2,   3, 146, 147,  19, 148]]) tensor([149])
tensor([[ 42, 137,   2, 226,  12,   3, 227, 228]]) tensor([155])
tensor([[  1,   2,   3,  92, 137,  19,   3,  45]]) tensor([185])
tensor([[  1,   2,   3,  33,  34,   5, 245]]) tensor([246])

In [14]:
import torch.nn as nn

In [19]:
class SimpleRNN(nn.Module):
  def __init__(self,vocab_size):
    super().__init__()
    self.embeddding=nn.Embedding(vocab_size,embedding_dim=50)
    self.rnn=nn.RNN(50,64,batch_first=True)
    self.fc=nn.Linear(64,vocab_size)

  def forward(self,question):
    embedded_question= self.embeddding(question)
    hidden,final= self.rnn(embedded_question)
    output= self.fc(final.squeeze(0))

    return output

In [28]:
x = nn.Embedding(324, embedding_dim=50)
y = nn.RNN(50, 64, batch_first=True)
#to prevent swap of batchlen and no of words in sentence swap

z = nn.Linear(64, 324)

a = dataset[0][0].reshape(1,6)
print("shape of a:", a.shape)
b = x(a)
print("shape of b:", b.shape)
c, d = y(b)
print("shape of c:", c.shape)
print("shape of d:", d.shape)

e = z(d.squeeze(0))  #removes batchlen dim

print("shape of e:", e.shape)

shape of a: torch.Size([1, 6])
shape of b: torch.Size([1, 6, 50])
shape of c: torch.Size([1, 6, 64])
shape of d: torch.Size([1, 1, 64])
shape of e: torch.Size([1, 324])

In [25]:
#define lr & epoch
learning_rate=0.001
epochs=50

In [26]:
#define model,loss & optimizer
model=SimpleRNN(len(vocab))

criterion=nn.CrossEntropyLoss()

optimizer=torch.optim.Adam(model.parameters(),lr=learning_rate)

In [27]:
#training loop
for epoch in range(epochs):
  total_loss=0

  for question,answer in dataloader:
    optimizer.zero_grad()

    #model
    output=model(question)
    #loss-> output shape(1,324),ans-(1)
    loss=criterion(output,answer[0])
    #backward pass
    loss.backward()
    #gradient update
    optimizer.step()

    total_loss+=loss.item()

  print(f"Epoch: {epoch+1}, Loss: {total_loss:4f}")

Epoch: 1, Loss: 526.820846
Epoch: 2, Loss: 458.116175
Epoch: 3, Loss: 380.413778
Epoch: 4, Loss: 318.864490
Epoch: 5, Loss: 267.958624
Epoch: 6, Loss: 220.555818
Epoch: 7, Loss: 177.386461
Epoch: 8, Loss: 139.024708
Epoch: 9, Loss: 107.137242
Epoch: 10, Loss: 83.070343
Epoch: 11, Loss: 63.805831
Epoch: 12, Loss: 50.584741
Epoch: 13, Loss: 40.347924
Epoch: 14, Loss: 32.489752
Epoch: 15, Loss: 26.807446
Epoch: 16, Loss: 22.283170
Epoch: 17, Loss: 18.754802
Epoch: 18, Loss: 16.218974
Epoch: 19, Loss: 13.623800
Epoch: 20, Loss: 11.729155
Epoch: 21, Loss: 10.260961
Epoch: 22, Loss: 9.037165
Epoch: 23, Loss: 8.039189
Epoch: 24, Loss: 7.202258
Epoch: 25, Loss: 6.461402
Epoch: 26, Loss: 5.800967
Epoch: 27, Loss: 5.281002
Epoch: 28, Loss: 4.771619
Epoch: 29, Loss: 4.370142
Epoch: 30, Loss: 3.999960
Epoch: 31, Loss: 3.674305
Epoch: 32, Loss: 3.366413
Epoch: 33, Loss: 3.114145
Epoch: 34, Loss: 2.880147
Epoch: 35, Loss: 2.671010
Epoch: 36, Loss: 2.477272
Epoch: 37, Loss: 2.306431
Epoch: 38, Loss: 2.143780
Epoch: 39, Loss: 2.002343
Epoch: 40, Loss: 1.872587
Epoch: 41, Loss: 1.752213
Epoch: 42, Loss: 1.642356
Epoch: 43, Loss: 1.538954
Epoch: 44, Loss: 1.444014
Epoch: 45, Loss: 1.359208
Epoch: 46, Loss: 1.278681
Epoch: 47, Loss: 1.202186
Epoch: 48, Loss: 1.134208
Epoch: 49, Loss: 1.070343
Epoch: 50, Loss: 1.009042

In [47]:
def predict(model,question,threshold=0.5):

  #conv que to no.
  numerical_question= text_to_indices(question,vocab)
  #tensor
  question_tensor=torch.tensor(numerical_question).unsqueeze(0)
  #send to model
  output=model(question_tensor)

  #conv logits to probab
  probability=torch.nn.functional.softmax(output,dim=1)

  #find index of max probab
  value,index=torch.max(probability,dim=1)


  if value< threshold:
    print("I dont know")

  print(list(vocab.keys())[index])

In [48]:
predict(model,"capital of france")

paris

In [43]:
vocab

{'<UNK>': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'who': 10,
 'wrote': 11,
 'to': 12,
 'kill': 13,
 'a': 14,
 'mockingbird': 15,
 'harper-lee': 16,
 'largest': 17,
 'planet': 18,
 'in': 19,
 'our': 20,
 'solar': 21,
 'system': 22,
 'jupiter': 23,
 'boiling': 24,
 'point': 25,
 'water': 26,
 'celsius': 27,
 '100': 28,
 'painted': 29,
 'mona': 30,
 'lisa': 31,
 'leonardo-da-vinci': 32,
 'square': 33,
 'root': 34,
 '64': 35,
 '8': 36,
 'chemical': 37,
 'symbol': 38,
 'for': 39,
 'gold': 40,
 'au': 41,
 'which': 42,
 'year': 43,
 'did': 44,
 'world': 45,
 'war': 46,
 'ii': 47,
 'end': 48,
 '1945': 49,
 'longest': 50,
 'river': 51,
 'nile': 52,
 'japan': 53,
 'tokyo': 54,
 'developed': 55,
 'theory': 56,
 'relativity': 57,
 'albert-einstein': 58,
 'freezing': 59,
 'fahrenheit': 60,
 '32': 61,
 'known': 62,
 'as': 63,
 'red': 64,
 'mars': 65,
 'author': 66,
 '1984': 67,
 'george-orwell': 68,
 'currency': 69,
 'united': 70,
 'kingdom': 71,
 'pound': 72,
 'india': 73,
 'delhi': 74,
 'discovered': 75,
 'gravity': 76,
 'newton': 77,
 'how': 78,
 'many': 79,
 'continents': 80,
 'are': 81,
 'there': 82,
 'on': 83,
 'earth': 84,
 '7': 85,
 'gas': 86,
 'do': 87,
 'plants': 88,
 'use': 89,
 'photosynthesis': 90,
 'co2': 91,
 'smallest': 92,
 'prime': 93,
 'number': 94,
 '2': 95,
 'invented': 96,
 'telephone': 97,
 'alexander-graham-bell': 98,
 'australia': 99,
 'canberra': 100,
 'ocean': 101,
 'pacific-ocean': 102,
 'speed': 103,
 'light': 104,
 'vacuum': 105,
 '299,792,458m/s': 106,
 'language': 107,
 'spoken': 108,
 'brazil': 109,
 'portuguese': 110,
 'penicillin': 111,
 'alexander-fleming': 112,
 'canada': 113,
 'ottawa': 114,
 'mammal': 115,
 'whale': 116,
 'element': 117,
 'has': 118,
 'atomic': 119,
 '1': 120,
 'hydrogen': 121,
 'tallest': 122,
 'mountain': 123,
 'everest': 124,
 'city': 125,
 'big': 126,
 'apple': 127,
 'newyork': 128,
 'planets': 129,
 'starry': 130,
 'night': 131,
 'vangogh': 132,
 'formula': 133,
 'h2o': 134,
 'italy': 135,
 'rome': 136,
 'country': 137,
 'famous': 138,
 'sushi': 139,
 'was': 140,
 'first': 141,
 'person': 142,
 'step': 143,
 'moon': 144,
 'armstrong': 145,
 'main': 146,
 'ingredient': 147,
 'guacamole': 148,
 'avocado': 149,
 'sides': 150,
 'does': 151,
 'hexagon': 152,
 'have': 153,
 '6': 154,
 'china': 155,
 'yuan': 156,
 'pride': 157,
 'and': 158,
 'prejudice': 159,
 'jane-austen': 160,
 'iron': 161,
 'fe': 162,
 'hardest': 163,
 'natural': 164,
 'substance': 165,
 'diamond': 166,
 'continent': 167,
 'by': 168,
 'area': 169,
 'asia': 170,
 'president': 171,
 'states': 172,
 'george-washington': 173,
 'bird': 174,
 'its': 175,
 'ability': 176,
 'mimic': 177,
 'sounds': 178,
 'parrot': 179,
 'longest-running': 180,
 'animated': 181,
 'tv': 182,
 'show': 183,
 'simpsons': 184,
 'vaticancity': 185,
 'most': 186,
 'moons': 187,
 'saturn': 188,
 'romeo': 189,
 'juliet': 190,
 'shakespeare': 191,
 'earths': 192,
 'atmosphere': 193,
 'nitrogen': 194,
 'bones': 195,
 'adult': 196,
 'human': 197,
 'body': 198,
 '206': 199,
 'metal': 200,
 'liquid': 201,
 'at': 202,
 'room': 203,
 'temperature': 204,
 'mercury': 205,
 'russia': 206,
 'moscow': 207,
 'electricity': 208,
 'benjamin-franklin': 209,
 'second-largest': 210,
 'land': 211,
 'color': 212,
 'ripe': 213,
 'banana': 214,
 'yellow': 215,
 'month': 216,
 '28': 217,
 'days': 218,
 'common': 219,
 'february': 220,
 'study': 221,
 'living': 222,
 'organisms': 223,
 'called': 224,
 'biology': 225,
 'home': 226,
 'great': 227,
 'wall': 228,
 'bees': 229,
 'collect': 230,
 'from': 231,
 'flowers': 232,
 'nectar': 233,
 'opposite': 234,
 'day': 235,
 'south': 236,
 'korea': 237,
 'seoul': 238,
 'bulb': 239,
 'edison': 240,
 'humans': 241,
 'breathe': 242,
 'survival': 243,
 'oxygen': 244,
 '144': 245,
 '12': 246,
 'pyramids': 247,
 'giza': 248,
 'egypt': 249,
 'sea': 250,
 'creature': 251,
 'eight': 252,
 'arms': 253,
 'octopus': 254,
 'holiday': 255,
 'celebrated': 256,
 'december': 257,
 '25': 258,
 'christmas': 259,
 'yen': 260,
 'legs': 261,
 'spider': 262,
 'sport': 263,
 'uses': 264,
 'net,': 265,
 'ball,': 266,
 'hoop': 267,
 'basketball': 268,
 'kangaroos': 269,
 'female': 270,
 'minister': 271,
 'uk': 272,
 'margaretthatcher': 273,
 'fastest': 274,
 'animal': 275,
 'cheetah': 276,
 'periodic': 277,
 'table': 278,
 'spain': 279,
 'madrid': 280,
 'closest': 281,
 'sun': 282,
 'father': 283,
 'computers': 284,
 'charlesbabbage': 285,
 'mexico': 286,
 'mexicocity': 287,
 'colors': 288,
 'rainbow': 289,
 'musical': 290,
 'instrument': 291,
 'black': 292,
 'white': 293,
 'keys': 294,
 'piano': 295,
 'americas': 296,
 '1492': 297,
 'christophercolumbus': 298,
 'disney': 299,
 'character': 300,
 'long': 301,
 'nose': 302,
 'grows': 303,
 'it': 304,
 'when': 305,
 'lying': 306,
 'pinocchio': 307,
 'directed': 308,
 'movie': 309,
 'titanic': 310,
 'jamescameron': 311,
 'superhero': 312,
 'also': 313,
 'dark': 314,
 'knight': 315,
 'batman': 316,
 'brasilia': 317,
 'fruit': 318,
 'king': 319,
 'fruits': 320,
 'mango': 321,
 'eiffel': 322,
 'tower': 323}